### ISSUE TITLE
Principles for Evaluating Pull Requests

### ISSUE THREAD

**Issue by alesr** [DevOpsGIG/documentation#2]
Describe the guidelines for a valid Pull Request.

**Comment by alesr** [comment]
The idea is to list a set of tips to help developers on preparing their PRs for review. And give material support for referencing good standards for Pull Request.

**Comment by JoanaMendesAgileCoach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fazer x](https://trello.com/c/0BbaRAMv/1-fazer-x)
